module.exports = Object.freeze({
    STATUS: {
        OK: 'OK',
        ERROR: 'ERROR',
        WARNING: 'WARNING'
    },
    QOE_INDEXES: {
        HIGHEST_BITRATE_POSSIBLE: 'HIGHEST_BITRATE_POSSIBLE',
        TOO_MANY_BITRATE_SWITCHES: 'TOO_MANY_BITRATE_SWITCHES',
        TOO_MANY_BUFFERING: 'TOO_MANY_BUFFERING'
    },
    TRIGGERS: {
        SCHEDULE: 'SCHEDULE',
        LOAD: 'LOAD',
        START_BUFFERING: 'START_BUFFERING',
        END_BUFFERING: 'END_BUFFERING',
        BITRATE_SWITCH: 'BITRATE_SWITCH'
    },
    THRESHOLDS: {
        SHORT_BUFFERING_EVENT_TIME: 500,
        SHORT_BUFFERING_EVENT_COUNT: 3,
        LONG_BUFFERING_EVENT_TIME: 1000,
        LONG_BUFFERING_EVENT_COUNT: 1,
        BITRATE_SWITCH_COUNT: 2,
    }
});